site_name: База знаний группы
site_url: https://savon13.github.io/baza-znaniy/
theme:
  name: material
  language: ru
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
  - Главная: index.md
  - Лекции: Лекции/README.md
  - Домашние задания: "Домашние задания/README.md"
  - Полезное: Полезное/README.md
