nav:
  - Главная: index.md
  - Лекции:
    - Обзор: Лекции/README.md
  - Домашние задания:
    - Обзор: "Домашние задания/README.md"
    - АП: "Домашние задания/АП/README.md"
    - Адвокатура: "Домашние задания/Адвокатура/README.md"
    - БЖД: "Домашние задания/БЖД/README.md"
    - ГП: "Домашние задания/ГП/README.md"
    - Инклюзивность: "Домашние задания/Инклюзивность/README.md"
    - КП: "Домашние задания/КП/README.md"
    - Красноречие: "Домашние задания/Красноречие/README.md"
    - ОФП: "Домашние задания/ОФП/README.md"
    - ПСО: "Домашние задания/ПСО/README.md"
    - Правоохр_органы: "Домашние задания/Правоохр_органы/README.md"
    - СоцПред: "Домашние задания/СоцПред/README.md"
    - УП: "Домашние задания/УП/README.md"
  - Полезное: Полезное/README.md
